/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.SystemAdministratorWorkArea;

import healthcare.Enterprise.Enterprise;
import healthcare.Department.Department;
import healthcare.Ecosystem.EcoSystem;
import healthcare.Network.CompositeNetwork;
import healthcare.Network.HospitalNetwork;
import healthcare.Network.Network;
import healthcare.Network.PharmaceuticalCompaniesNetwork;
import healthcare.Network.SocialNetwork;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Muddassar
 */
public class SystemAdministratorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form SystemAdministratorWorkAreaJPanel
     */
    public SystemAdministratorWorkAreaJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.populateTree();
    }
    
    private void populateTree() {

        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        ArrayList<Network> networkList = system.getNetworkList();
        Network network;
        
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode(system);
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.insert(networks, 0);

        
        
        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            
            
            this.recurseNetworkNodes(networks, network);
        }
        model.reload();
        
    }
    
    private void recurseNetworkNodes(DefaultMutableTreeNode parentNode, Network networkNode)
    {
        DefaultMutableTreeNode currentNode = new DefaultMutableTreeNode(networkNode);
        parentNode.add(currentNode);
        if(networkNode.getChildNetworks()==null)
        {
            DefaultMutableTreeNode enterpriseNode;
            DefaultMutableTreeNode organizationNode;
            ArrayList<Enterprise> enterpriseList;
            ArrayList<Department> organizationList;
            Enterprise enterprise;
            Department organization;
            enterpriseList = networkNode.getEnterpriseDirectory().getEnterpriseList();

                for (int j = 0; j < enterpriseList.size(); j++) 
                {
                    enterprise = enterpriseList.get(j);
                    enterpriseNode = new DefaultMutableTreeNode(enterprise);
                    currentNode.insert(enterpriseNode, j);

                    organizationList = enterprise.getDepartmentDirectory().getOrganizationList();
                        for (int k = 0; k < organizationList.size(); k++) 
                        {
                            organization = organizationList.get(k);
                            organizationNode = new DefaultMutableTreeNode(organization);
                            enterpriseNode.insert(organizationNode, k);
                        }
                }
        }
        else
        {
            for(Network net : networkNode.getChildNetworks())
            {
                recurseNetworkNodes(currentNode, net);
            }
        
        }
    
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterpriseAdmin = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        selectedNodeJLabel = new javax.swing.JLabel();
        btnManageRegionalNetwork = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.setEnabled(false);
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btnManageEnterpriseAdmin.setText("Manage Enterprise Admin");
        btnManageEnterpriseAdmin.setEnabled(false);
        btnManageEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdminActionPerformed(evt);
            }
        });

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.setEnabled(false);
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        jLabel1.setText("Selected Node:");

        selectedNodeJLabel.setText("<view_selected_node>");

        btnManageRegionalNetwork.setText("Manage RegionalNetwork");
        btnManageRegionalNetwork.setEnabled(false);
        btnManageRegionalNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegionalNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(selectedNodeJLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnManageEnterpriseAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageNetwork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnManageRegionalNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selectedNodeJLabel))
                .addGap(72, 72, 72)
                .addComponent(btnManageRegionalNetwork)
                .addGap(18, 18, 18)
                .addComponent(btnManageNetwork)
                .addGap(28, 28, 28)
                .addComponent(btnManageEnterpriseAdmin)
                .addGap(28, 28, 28)
                .addComponent(btnManageEnterprise)
                .addGap(143, 143, 143))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreevalueChangedAction(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JTreevalueChangedAction(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreevalueChangedAction
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            selectedNodeJLabel.setText(selectedNode.toString() + " " +selectedNode.getUserObject().getClass().toString());
        }
        if(selectedNode.getUserObject() instanceof EcoSystem 
                || selectedNode.getUserObject() instanceof CompositeNetwork)
        {
            btnManageRegionalNetwork.setEnabled(true);
            btnManageNetwork.setEnabled(true);
            btnManageEnterprise.setEnabled(false);
            btnManageEnterpriseAdmin.setEnabled(false);
        }
        if(selectedNode.getUserObject() instanceof HospitalNetwork
                || selectedNode.getUserObject() instanceof SocialNetwork
                || selectedNode.getUserObject() instanceof PharmaceuticalCompaniesNetwork)
        {
            btnManageRegionalNetwork.setEnabled(false);
            btnManageNetwork.setEnabled(false);
            btnManageEnterprise.setEnabled(true);
            btnManageEnterpriseAdmin.setEnabled(true);
            
        }
        if(selectedNode.getUserObject() instanceof Enterprise || selectedNode.getUserObject() instanceof Department)
        {
            btnManageRegionalNetwork.setEnabled(false);
            btnManageNetwork.setEnabled(false);
            btnManageEnterprise.setEnabled(false);
            btnManageEnterpriseAdmin.setEnabled(false);
            
        }
    }//GEN-LAST:event_JTreevalueChangedAction

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        Network network = null;
        if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
                network = (Network)selectedNode.getUserObject();
            }
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system, network);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        Network network = null;
        if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
            network = (Network)selectedNode.getUserObject();
            
        }
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseAdminActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed

        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        Network network = null;
        if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
            network = (Network)selectedNode.getUserObject();
            
        }
        
        
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageRegionalNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegionalNetworkActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        Network network = null;
        if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
            network = (Network)selectedNode.getUserObject();
            
        }
        
        ManageRegionalNetworksJPanel manageSubnetworkJPanel = new ManageRegionalNetworksJPanel(userProcessContainer, system, network);
        userProcessContainer.add("ManageSubnetworkJPanel", manageSubnetworkJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageRegionalNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageEnterpriseAdmin;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageRegionalNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
