/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.DoctorWorkArea;

import healthcare.Department.DoctorDepartment;
import healthcare.Department.LabDepartment;
import healthcare.Department.PatientDepartment;
import healthcare.Department.PharmaceuticalDrugRegulatoryDepartment;
import healthcare.Department.PharmacyDepartment;
import healthcare.Ecosystem.EcoSystem;
import healthcare.Enterprise.Enterprise;
import healthcare.Network.Network;
import healthcare.Network.PharmaceuticalCompaniesNetwork;
import healthcare.Person.Doctor;
import healthcare.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Muddassar
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DoctorDepartment doctorDepartment;
    private LabDepartment labDepartment;
    private PharmacyDepartment pharmacyDepartment;
    private PatientDepartment patientDepartment;
    private Enterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form DoctorWorkArea
     */
    public DoctorWorkAreaJPanel(JPanel upc, UserAccount account, DoctorDepartment docDep
            , LabDepartment lab,PharmacyDepartment pharmacy, PatientDepartment patDept
            , EcoSystem system, Enterprise enterprise ) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = account;
        this.doctorDepartment = docDep;
        this.labDepartment = lab;
        this.pharmacyDepartment = pharmacy;
        this.patientDepartment = patDept;
        this.enterprise = enterprise;
        this.system = system;
        if(this.userAccount != null && (this.userAccount.getPerson() instanceof Doctor))
        {
            Doctor d = (Doctor)this.userAccount.getPerson();
            if(d.getSpeciality() == null)
            {
                lblAlert.setVisible(true);
            }
            else
            {
                lblAlert.setVisible(false);
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAllPatients = new javax.swing.JButton();
        btnManageMyPatients = new javax.swing.JButton();
        btnReportDrugs = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        lblAlert = new javax.swing.JLabel();
        btnPatientMonitor = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageAllPatients.setText("Manage All Patients");
        btnManageAllPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAllPatientsActionPerformed(evt);
            }
        });
        add(btnManageAllPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 107, 200, -1));

        btnManageMyPatients.setText("Manage My Patients");
        btnManageMyPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMyPatientsActionPerformed(evt);
            }
        });
        add(btnManageMyPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 163, 200, -1));

        btnReportDrugs.setText("Report Drugs");
        btnReportDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDrugsActionPerformed(evt);
            }
        });
        add(btnReportDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, -1));

        btnProfile.setText("Manage Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 49, 200, -1));

        lblAlert.setForeground(new java.awt.Color(255, 51, 51));
        lblAlert.setText("Update profile before proceeding");
        add(lblAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btnPatientMonitor.setText("Patient Monitor");
        btnPatientMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientMonitorActionPerformed(evt);
            }
        });
        add(btnPatientMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAllPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAllPatientsActionPerformed
        // TODO add your handling code here:
        ManageAllAdmittedPatientsJPanel maapjp = new ManageAllAdmittedPatientsJPanel(userProcessContainer,userAccount, doctorDepartment);
        userProcessContainer.add("ManageAllAdmittedPatientsJPanel", maapjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAllPatientsActionPerformed

    private void btnManageMyPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMyPatientsActionPerformed
        // TODO add your handling code here:
        ManageMyPatientsJPanel mmpjp = new ManageMyPatientsJPanel(userProcessContainer,userAccount, doctorDepartment, labDepartment, pharmacyDepartment,enterprise, system);
        userProcessContainer.add("ManageMyPatientsJPanel", mmpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMyPatientsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        
        ManageProfileJPanel mpjp = new ManageProfileJPanel(userProcessContainer, (Doctor)this.userAccount.getPerson());
        userProcessContainer.add("ManageProfileJPanel", mpjp);
        lblAlert.setVisible(false);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);

    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnReportDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDrugsActionPerformed
        // TODO add your handling code here:
        ReportDrugJPanel mpjp = new ReportDrugJPanel(userProcessContainer,this.pharmacyDepartment,userAccount, system, enterprise);
        userProcessContainer.add("ReportDrugJPanel", mpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportDrugsActionPerformed

    private void btnPatientMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientMonitorActionPerformed
        // TODO add your handling code here:
        PatientMonitorJPanel mpjp = new PatientMonitorJPanel(userProcessContainer,this.patientDepartment);
        userProcessContainer.add("PatientMonitorJPanel", mpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPatientMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAllPatients;
    private javax.swing.JButton btnManageMyPatients;
    private javax.swing.JButton btnPatientMonitor;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReportDrugs;
    private javax.swing.JLabel lblAlert;
    // End of variables declaration//GEN-END:variables
}
