/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.DoctorWorkArea;

import healthcare.CommunicationBroadcast.CommunicationVisitor;
import healthcare.CommunicationBroadcast.ICommunicationVisitor;
import healthcare.Department.DepartmentType;
import healthcare.Department.PharmaceuticalDrugRegulatoryDepartment;
import healthcare.Department.PharmacyDepartment;
import healthcare.Drug.Drug;
import healthcare.Ecosystem.EcoSystem;
import healthcare.Enterprise.Enterprise;
import healthcare.Network.Network;
import healthcare.Network.PharmaceuticalCompaniesNetwork;
import healthcare.UserAccount.UserAccount;
import healthcare.WorkQueue.DrugReportWorkRequest;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Muddassar
 */
public class ReportDrugJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private PharmacyDepartment pharmacyDepartment;
    private UserAccount userAccount;
    private EcoSystem system;
    private Enterprise enterprise;
    private boolean isDrugLoaded;
    /**
     * Creates new form ReportDrugJPanel
     */
    public ReportDrugJPanel(JPanel upc, PharmacyDepartment pharmacyDepartment, UserAccount account, EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.pharmacyDepartment = pharmacyDepartment;
        this.userAccount = account;
        this.system = system;
        this.enterprise = enterprise;
        this.populateDrugs();
    }
    
    private void populateDrugs()
    {
        cmbDrugs.removeAllItems();
        for(Drug drug : pharmacyDepartment.getDrugCatalog().getDrugList())
        {
            cmbDrugs.addItem(drug);
        }
        isDrugLoaded = true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDrugs = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDrugReport = new javax.swing.JTextArea();
        btnSendAlert = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();

        jLabel1.setText("Report Drug");

        cmbDrugs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrugsActionPerformed(evt);
            }
        });

        jLabel2.setText("Drugs");

        jLabel3.setText("Drug Report");

        txtDrugReport.setColumns(20);
        txtDrugReport.setRows(5);
        jScrollPane1.setViewportView(txtDrugReport);

        btnSendAlert.setText("Send Report");
        btnSendAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendAlertActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Enterprise");

        txtEnterprise.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtEnterprise)
                                    .addGap(9, 9, 9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)
                                .addComponent(cmbDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(28, 28, 28)
                        .addComponent(btnSendAlert)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendAlert)
                    .addComponent(btnBack))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendAlertActionPerformed
        // TODO add your handling code here:
        if(txtDrugReport.getText().isEmpty() || cmbDrugs.getSelectedIndex()<0)
        {
            JOptionPane.showMessageDialog(null,"Please input valid values");
            return;
        }
        CommunicationVisitor visitor = new CommunicationVisitor();
        Drug drug = (Drug)cmbDrugs.getSelectedItem();
        DrugReportWorkRequest wr = new DrugReportWorkRequest(this.enterprise);
        wr.setSender(this.userAccount);
        wr.setDrug(drug);
        wr.setDrugReport(txtDrugReport.getText());
        this.userAccount.getWorkQueue().getWorkRequestList().add(wr);
        visitor.setWorkRequest(wr);
        system.broadcastToHospitalEnterprisesWorkRequest(visitor);
        Logger logger = Logger.getLogger(this.getClass().toString());
        logger.log(Level.INFO,String.format("Drug Alert raised for Drug:%s by Manufacturer",drug.getName(),drug.getManufacturer() ));
        JOptionPane.showMessageDialog(null,"Alert message has been raised");
    }//GEN-LAST:event_btnSendAlertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrugsActionPerformed
        // TODO add your handling code here:
        if(isDrugLoaded && cmbDrugs.getSelectedIndex() >= 0)
        {
            Drug drug = (Drug)cmbDrugs.getSelectedItem();
            txtEnterprise.setText(drug.getManufacturer());
        }
    }//GEN-LAST:event_cmbDrugsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendAlert;
    private javax.swing.JComboBox cmbDrugs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDrugReport;
    private javax.swing.JTextField txtEnterprise;
    // End of variables declaration//GEN-END:variables
}
