/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.LabAssistantWorkArea;

import healthcare.Department.LabDepartment;
import healthcare.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Muddassar
 */
public class LabAssistantWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private LabDepartment labdepartment;
    private UserAccount userAccount;
    /**
     * Creates new form LabAssistantWorkArea
     */
    public LabAssistantWorkArea(JPanel upc, LabDepartment department, UserAccount account) {
        initComponents();
        this.userProcessContainer = upc;
        this.labdepartment = department;
        this.userAccount = account;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAllTests = new javax.swing.JButton();
        btnManageMyTests = new javax.swing.JButton();

        btnManageAllTests.setText("Manage All Tests");
        btnManageAllTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAllTestsActionPerformed(evt);
            }
        });

        btnManageMyTests.setText("Manage My Tests");
        btnManageMyTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMyTestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageMyTests)
                    .addComponent(btnManageAllTests))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnManageAllTests)
                .addGap(18, 18, 18)
                .addComponent(btnManageMyTests)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAllTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAllTestsActionPerformed
        // TODO add your handling code here:
        ManageAllTestsJPanel matjp = new ManageAllTestsJPanel(userProcessContainer, this.labdepartment, this.userAccount);
        userProcessContainer.add("ManageAllTestsJPanel", matjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAllTestsActionPerformed

    private void btnManageMyTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMyTestsActionPerformed
        // TODO add your handling code here:
        ManageMyTestsJPanel mmtjp = new ManageMyTestsJPanel(userProcessContainer, this.userAccount);
        userProcessContainer.add("ManageAllTestsJPanel", mmtjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMyTestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAllTests;
    private javax.swing.JButton btnManageMyTests;
    // End of variables declaration//GEN-END:variables
}
