/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.LabAssistantWorkArea;

import healthcare.Commons.WorkRequestStatusType;
import healthcare.Department.Department;
import healthcare.Department.LabDepartment;
import healthcare.Patient.Patient;
import healthcare.UserAccount.UserAccount;
import healthcare.WorkQueue.LabTestWorkRequest;
import healthcare.WorkQueue.MedicationWorkRequest;
import healthcare.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muddassar
 */
public class ManageAllTestsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private LabDepartment labdepartment;
    private UserAccount userAccount;
    /**
     * Creates new form ManageAllTestsJPanel
     */
    public ManageAllTestsJPanel(JPanel upc, LabDepartment department, UserAccount account) {
        initComponents();
        this.userProcessContainer = upc;
        this.labdepartment = department;
        this.userAccount = account;
        this.populateTable();
    }

    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblAllTests.getModel();
        model.setRowCount(0);
        for(WorkRequest request : this.labdepartment.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof MedicationWorkRequest && request.getStatus().equals(WorkRequestStatusType.Created))
            {
                Object[] row = new Object[3];
                Patient patient = ((MedicationWorkRequest)request).getPatient();
                row[0] = request; 
                row[1] = patient;
                row[2] = request.getSender();
                model.addRow(row);
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllTests = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAssigntoMe = new javax.swing.JButton();

        tblAllTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Patient", "Req Doctor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllTests);
        if (tblAllTests.getColumnModel().getColumnCount() > 0) {
            tblAllTests.getColumnModel().getColumn(0).setResizable(false);
            tblAllTests.getColumnModel().getColumn(1).setResizable(false);
            tblAllTests.getColumnModel().getColumn(2).setResizable(false);
        }

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssigntoMe.setText("Assign to Me");
        btnAssigntoMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssigntoMe)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAssigntoMe))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigntoMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAllTests.getSelectedRow();
        if(selectedRow < 0)
        {
	    JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        WorkRequest wr = (WorkRequest)tblAllTests.getValueAt(selectedRow, 0);
        wr.setReceiver(userAccount);
        wr.setStatus(WorkRequestStatusType.Processing);
        this.userAccount.getWorkQueue().getWorkRequestList().add(wr);
        Logger logger = Logger.getLogger(this.getClass().toString());
        logger.log(Level.INFO,String.format("Lab Test assigned to:%s ", this.userAccount.getPerson().getName()));
        this.populateTable();
    }//GEN-LAST:event_btnAssigntoMeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllTests;
    // End of variables declaration//GEN-END:variables
}
