/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.PharmaceuticalDrugRegulatorWorkArea;

import healthcare.Department.PharmaceuticalDrugRegulatoryDepartment;
import healthcare.Drug.Drug;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muddassar
 */
public class ManageDrugsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmaceuticalDrugRegulatoryDepartment drugRegulatoryDepartment;
    private String manufacturer;
    /**
     * Creates new form ManageDrugsJPanel
     */
    public ManageDrugsJPanel(JPanel upc, PharmaceuticalDrugRegulatoryDepartment drugSupplierDepartment, String manufacturer) {
        initComponents();
        this.userProcessContainer = upc;
        this.drugRegulatoryDepartment = drugSupplierDepartment;
        this.manufacturer = manufacturer;
        this.populateDrugTable();
    }
    
    private void populateDrugTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblDrugCatalog.getModel();
        
        model.setRowCount(0);
        
        for (Drug drug : this.drugRegulatoryDepartment.getDrugCatalog().getDrugList()){
            Object[] row = new Object[3];
            row[0] = drug.getName();
            row[1] = drug.getManufacturer();
            String remsStatus = "NO REMS";
            if(drug.getMedicationGuidelines().getComplianceGuidelines().size() > 0)
            {
                remsStatus = "REMS APPLICABLE";
            }
            row[2] = remsStatus;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugCatalog = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        btnAddDrug = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tblDrugCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Manufacturer", "REMS Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugCatalog);
        if (tblDrugCatalog.getColumnModel().getColumnCount() > 0) {
            tblDrugCatalog.getColumnModel().getColumn(0).setResizable(false);
            tblDrugCatalog.getColumnModel().getColumn(1).setResizable(false);
            tblDrugCatalog.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Drug Catalog");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewDetail.setText("View Detail");

        btnAddDrug.setText("AddDrug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(26, 26, 26)
                                .addComponent(btnViewDetail)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddDrug))
                            .addComponent(btnRefresh))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewDetail)
                    .addComponent(btnAddDrug))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:
        AddDrugJPanel adjp = new AddDrugJPanel(userProcessContainer, this.drugRegulatoryDepartment.getDrugCatalog(), this.manufacturer);
        userProcessContainer.add("AddDrugJPanel", adjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        this.populateDrugTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrugCatalog;
    // End of variables declaration//GEN-END:variables
}
