/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.PharmaceuticalDrugRegulatorWorkArea;

import healthcare.Department.PharmaceuticalDrugRegulatoryDepartment;
import healthcare.Enterprise.Enterprise;
import healthcare.WorkQueue.DrugReportWorkRequest;
import healthcare.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muddassar
 */
public class TrackDrugReportsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise drugEnterprise;
    /**
     * Creates new form TrackDrugReportsJPanel
     */
    public TrackDrugReportsJPanel(JPanel upc, Enterprise enterprise ) {
        initComponents();
        this.userProcessContainer = upc;
        
        this.drugEnterprise = enterprise;
        this.populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblDrugReports.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : this.drugEnterprise.getWorkQueue().getWorkRequestList())
        {
            if(wr instanceof DrugReportWorkRequest)
            {
                Object[] row = new Object[3];
                row[0] = ((DrugReportWorkRequest)wr).getDrug();
                row[1] = ((DrugReportWorkRequest)wr).getDrugReport();
                row[2] = wr.getSender();
                model.addRow(row);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugReports = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alerts");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        tblDrugReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Report", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugReports);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, 430, 220));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrugReports;
    // End of variables declaration//GEN-END:variables
}
