/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcare.UserInterface.PharmacyWorkArea;

import healthcare.Department.DepartmentType;
import healthcare.Department.PharmaceuticalDrugRegulatoryDepartment;
import healthcare.Department.PharmacyDepartment;
import healthcare.Drug.Drug;
import healthcare.Enterprise.Enterprise;
import healthcare.Network.PharmaceuticalCompaniesNetwork;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muddassar
 */
public class ManageDrugInventoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmaceuticalCompaniesNetwork pharmaNetwork;
    private PharmacyDepartment pharmacyDepartment;
    boolean isLoaded = false;
    /**
     * Creates new form ManageDrugInventoryJPanel
     */
    public ManageDrugInventoryJPanel(JPanel upc, PharmaceuticalCompaniesNetwork network, PharmacyDepartment dept) {
        initComponents();
        this.userProcessContainer = upc;
        this.pharmaNetwork = network;
        this.pharmacyDepartment = dept;
        this.populateDrugInventory();
        this.populatePharmaceuticalCompanies();
    }

    
    private void populateDrugInventory()
    {
        DefaultTableModel model = (DefaultTableModel)tblDrugInventory.getModel();
        
            model.setRowCount(0);
        for(Drug drug : this.pharmacyDepartment.getDrugCatalog().getDrugList())
        {
            Object[] row = new Object[3];
            row[0] = drug.getName();
            row[1] = drug.getManufacturer();
            row[2] = drug.getDrugStatus();
            model.addRow(row);
        }
    }
    
    private void populatePharmaceuticalCompanies()
    {
        
        for(Enterprise ent : this.pharmaNetwork.getEnterpriseDirectory().getEnterpriseList())
        {
            cmbDrugCompany.addItem(ent);
        }
        cmbDrugCompany.setSelectedIndex(0);
        isLoaded = true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugInventory = new javax.swing.JTable();
        cmbDrugCompany = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDrugs = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        chkSubscribeToAlerts = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDrugInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Manufacturer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugInventory);
        if (tblDrugInventory.getColumnModel().getColumnCount() > 0) {
            tblDrugInventory.getColumnModel().getColumn(0).setResizable(false);
            tblDrugInventory.getColumnModel().getColumn(1).setResizable(false);
            tblDrugInventory.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 410, 96));

        cmbDrugCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrugCompanyActionPerformed(evt);
            }
        });
        add(cmbDrugCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 114, 166, -1));

        jLabel1.setText("Manufacturer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        jScrollPane2.setViewportView(listDrugs);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 147, 166, 73));

        jLabel2.setText("Drugs");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 167, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 287, -1, -1));

        chkSubscribeToAlerts.setText("Subscribe To Alerts");
        add(chkSubscribeToAlerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 232, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDrugCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrugCompanyActionPerformed
        // TODO add your handling code here:
        
        if(isLoaded)
        {
            Enterprise ent = (Enterprise)cmbDrugCompany.getSelectedItem();
            PharmaceuticalDrugRegulatoryDepartment dept = (PharmaceuticalDrugRegulatoryDepartment)ent.getDepartment(DepartmentType.PharmaceuticalDrugRegulatoryDepartment);
            DefaultListModel dlm = new DefaultListModel();
            for(Drug drug : dept.getDrugCatalog().getDrugList())
                {
                    dlm.addElement(drug);
                }
            listDrugs.setModel(dlm);
        }
    }//GEN-LAST:event_cmbDrugCompanyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.pharmacyDepartment.getDrugCatalog().getDrugList().addAll( listDrugs.getSelectedValuesList());
        List<Drug> drugList = listDrugs.getSelectedValuesList();
        Enterprise ent = (Enterprise)cmbDrugCompany.getSelectedItem();
        PharmaceuticalDrugRegulatoryDepartment dept = (PharmaceuticalDrugRegulatoryDepartment)ent
                .getDepartment(DepartmentType.PharmaceuticalDrugRegulatoryDepartment);
        
        if(chkSubscribeToAlerts.isSelected())
        {
            for(Drug drug : drugList )
            {
                dept.getDrugUpdateSubscriptions().put(drug, this.pharmacyDepartment);
            }
        }
        JOptionPane.showMessageDialog(null,"Drugs added");
        this.populateDrugInventory();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox chkSubscribeToAlerts;
    private javax.swing.JComboBox cmbDrugCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listDrugs;
    private javax.swing.JTable tblDrugInventory;
    // End of variables declaration//GEN-END:variables
}
